name: 'Silent Sound Generator'

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        updateAssemblyInfo: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -p:Version=${{ env.fullSemVer }}
      
    - name: Publish
      run: dotnet publish SilentSoundGenerator/SilentSoundGenerator.csproj -c Release -r win-x64 --self-contained -p:Version=${{ env.fullSemVer }} -o "./publish"

    - uses: vimtor/action-zip@v1.2
      with:
        files: ./publish/
        dest: ./release/silent-sound-generator-${{ env.fullSemVer }}.zip

    - name: Bump version and push tag
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ env.fullSemVer }}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./release/silent-sound-generator-${{ env.fullSemVer }}.zip
        name: v${{ env.fullSemVer }}
        tag_name: v${{ env.fullSemVer }}
        make_latest: true
