name: 'Silent Sound Generator'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.3
      with:
        versionSpec: '5.x'

    - name: Generate version using GitVersion
      id: gitversion
      run: gitversion /output json /showvariable FullSemVer

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -p:Version=${{ steps.gitversion.outputs.FullSemVer }}

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained -p:Version=${{ steps.gitversion.outputs.FullSemVer }}

    - name: Zip published output
      run: Compress-Archive -Path ./bin/Release/net8.0-windows/win-x64/publish/* -DestinationPath ./silent-sound-generator-${{ steps.gitversion.outputs.FullSemVer }}.zip

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.FullSemVer }}
        release_name: "Silent Sound Generator ${{ steps.gitversion.outputs.FullSemVer }}"
        body: "Automatischer Release für Version ${{ steps.gitversion.outputs.FullSemVer }}"
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./bin/Release/net8.0-windows/win-x64/publish
        asset_name: silent-sound-generator-${{ steps.gitversion.outputs.FullSemVer }}.zip
        asset_content_type: application/zip